services:
  postgres:
    image: postgres:16
    container_name: proyectorestaurante_postgres
    restart: always
    environment:
      POSTGRES_DB: ProyectoGRestaurantes3
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: proyectorestaurante_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: